# Generated by Django 3.1.2 on 2020-11-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20201127_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bill',
        ),
    ]
