# Generated by Django 3.1.2 on 2020-10-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategory',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='incomecategory',
            table='incomecategory',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.incomecategory')),
            ],
            options={
                'db_table': 'income',
            },
        ),
    ]
