# Generated by Django 3.1.2 on 2020-10-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20201011_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Income',
        ),
    ]
